"use client";
import {useEffect,useState} from "react";
import {api} from "@/lib/api";
type Alert={id:number;type:string;message:string;product_id:number|null;created_at:string};
export default function AlertsPage(){const[alerts,setAlerts]=useState<Alert[]>([]);const[storeId,setStoreId]=useState<number|null>(null);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
async function load(){setLoading(true);try{const{user}=await api<{user:{store_id:number|null}}>("/auth/me");if(!user.store_id)throw new Error("No store is associated with this account");setStoreId(user.store_id);const d=await api<{alerts:Alert[]}>(`/alerts?store_id=${user.store_id}`);setAlerts(d.alerts)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load alerts")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function generate(){if(!storeId)return;try{await api(`/alerts/generate-low-stock?store_id=${storeId}`,{method:"POST"});setMessage("Low-stock alerts refreshed.");load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to generate alerts")}}
async function resolve(id:number){if(!storeId)return;try{await api(`/alerts/resolve?store_id=${storeId}&id=${id}`,{method:"POST"});setMessage("Alert resolved.");load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to resolve alert")}}
return <main className="min-h-screen bg-[#0b0b0b] p-5 text-white md:p-8"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><h1 className="text-2xl font-semibold">Alerts</h1><button onClick={generate} className="rounded-xl bg-orange-500 px-4 py-2 text-sm font-semibold text-black">Refresh low stock</button></div>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-orange-300">{message}</p>}<div className="mt-6 space-y-3">{loading?<p className="py-12 text-center text-white/30">Loading...</p>:alerts.map(a=><article key={a.id} className="rounded-2xl border border-white/10 bg-[#151515] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase text-orange-400">{a.type}</p><p className="mt-2">{a.message}</p><p className="mt-2 text-xs text-white/30">{new Date(a.created_at).toLocaleString()}</p></div><button onClick={()=>resolve(a.id)} className="text-sm text-green-400">Resolve</button></div></article>)}{!loading&&!alerts.length&&<div className="rounded-2xl border border-white/10 bg-[#151515] p-10 text-center text-white/30">No open alerts.</div>}</div></div></main>}
