"use client";
import { useEffect, useState } from "react";
const tabs=["Daily","Monthly","Yearly"];
type Report={summary:{totalSales:number|string;totalProfit:number|string;transactions:number};payments:{payment:string;amount:number|string;transactions:number}[];topItems:{name:string;quantity:number;sales:number|string}[];employees:{employeeName:string;transactions:number;sales:number|string}[];trend:{date:string;sales:number|string}[]};
const money=(v:number|string)=>`₦${Number(v).toLocaleString()}`;
export default function ReportPage(){const [tab,setTab]=useState("Daily");const [data,setData]=useState<Report|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");async function load(){setLoading(true);try{const r=await fetch(`/api/reports?period=${tab.toLowerCase()}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to generate report");setData(d)}catch(e){setMessage(e instanceof Error?e.message:"Unable to generate report")}finally{setLoading(false)}}useEffect(()=>{load()},[tab]);const max=Math.max(...(data?.trend||[]).map(x=>Number(x.sales)),1);return <main className="min-h-screen bg-[#0b0b0b] p-5 text-white md:p-8"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-semibold">Reports</h1>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-orange-300">{message}</p>}<div className="mt-6 flex gap-2 border-b border-white/10">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-3 text-sm ${tab===t?"border-b-2 border-orange-500 text-orange-400":"text-white/45"}`}>{t}</button>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{[["TOTAL SALES",money(data?.summary.totalSales||0)],["TOTAL PROFIT",money(data?.summary.totalProfit||0)],["TRANSACTIONS",String(data?.summary.transactions||0)]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-[#151515] p-5"><p className="text-xs text-white/40">{a}</p><p className="mt-2 text-2xl font-semibold">{loading?"…":b}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Section title="Payment Breakdown"><div className="space-y-3">{data?.payments.length?data.payments.map(p=><div key={p.payment} className="flex justify-between rounded-lg bg-white/5 p-3"><span>{p.payment}</span><span>{money(p.amount)}</span></div>):<Placeholder text="No payment data yet."/>}</div></Section><Section title="Top Items"><Table headers={["ITEM","QTY SOLD","REVENUE"]} rows={(data?.topItems||[]).map(x=>[x.name,String(x.quantity),money(x.sales)])}/></Section><Section title="Employee Performance"><Table headers={["NAME","TRANSACTIONS","TOTAL SALES"]} rows={(data?.employees||[]).map(x=>[x.employeeName,String(x.transactions),money(x.sales)])}/></Section><Section title="Last 7 Days — Sales Trend"><div className="flex h-48 items-end gap-2 rounded-xl bg-[#101010] p-5">{(data?.trend||[]).map(x=><div key={x.date} className="group flex flex-1 flex-col items-center justify-end"><div className="w-full rounded-t bg-orange-500/80" title={`${x.date}: ${money(x.sales)}`} style={{height:`${Math.max(Number(x.sales)/max*100,Number(x.sales)?4:1)}%`}}/><span className="mt-2 text-[9px] text-white/30">{x.date.slice(5)}</span></div>)}</div></Section></div>{tab==="Yearly"&&<Section title="Yearly view"><Placeholder text="Yearly report currently uses the last 365 days of completed sales."/></Section>}</div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-[#151515] p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>}
function Placeholder({text}:{text:string}){return <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">{text}</div>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-white/40"><tr>{headers.map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-t border-white/5">{r.map((v,j)=><td key={j} className="px-3 py-3">{v}</td>)}</tr>):<tr><td colSpan={headers.length} className="px-3 py-8 text-center text-white/30">No data yet</td></tr>}</tbody></table></div>}
