"use client";
import { FormEvent,useEffect,useState } from "react";
import { api } from "@/lib/api";
type Product={id:number;name:string;price:string|number;stock_quantity:number;low_stock_threshold:number|null};
type Store={store_id:number|null};
export default function InventoryPage(){const[items,setItems]=useState<Product[]>([]);const[storeId,setStoreId]=useState<number|null>(null);const[form,setForm]=useState({name:"",price:"",stock:"0",threshold:"0"});const[editing,setEditing]=useState<number|null>(null);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
async function load(){setLoading(true);try{const{user}=await api<{user:Store}>("/auth/me");if(!user.store_id)throw new Error("No store is associated with this account");setStoreId(user.store_id);const d=await api<{products:Product[]}>(`/product/list?store_id=${user.store_id}`);setItems(d.products)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load inventory")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
function reset(){setForm({name:"",price:"",stock:"0",threshold:"0"});setEditing(null)}
async function save(e:FormEvent){e.preventDefault();if(!storeId)return;try{const body={store_id:storeId,name:form.name,price:Number(form.price),stock_quantity:Number(form.stock),low_stock_threshold:Number(form.threshold)};if(editing)await api(`/product/update`,{method:"PATCH",json:{...body,id:editing}});else await api("/product/create",{method:"POST",json:body});setMessage(editing?"Product updated.":"Product created.");reset();load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to save product")}}
async function adjust(id:number,change:number){if(!storeId)return;try{await api("/product/adjust",{method:"POST",json:{store_id:storeId,id,quantity_change:change,reason:"Manual stock adjustment"}});setMessage("Stock adjusted.");load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to adjust stock")}}
async function remove(id:number){if(!storeId||!confirm("Delete this product?"))return;try{await api("/product/delete",{method:"DELETE",json:{store_id:storeId,id}});setMessage("Product deleted.");load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to delete product")}}
function edit(p:Product){setEditing(p.id);setForm({name:p.name,price:String(p.price),stock:String(p.stock_quantity),threshold:String(p.low_stock_threshold??0)})}
return <main className="min-h-screen bg-[#0b0b0b] p-5 text-white md:p-8"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-semibold">Inventory</h1>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-orange-300">{message}</p>}<form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-[#151515] p-5 md:grid-cols-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Product name" className="field"/><input required min="0" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Price" className="field"/><input required min="0" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} placeholder="Opening stock" className="field"/><input min="0" type="number" value={form.threshold} onChange={e=>setForm({...form,threshold:e.target.value})} placeholder="Low-stock threshold" className="field"/><div className="flex gap-2 md:col-span-4"><button className="rounded-xl bg-orange-500 px-4 py-3 text-sm font-semibold text-black">{editing?"Save Changes":"Add Product"}</button>{editing&&<button type="button" onClick={reset} className="rounded-xl bg-white/10 px-4 py-3 text-sm">Cancel</button>}</div></form><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10 bg-[#151515] p-5"><table className="w-full text-left text-sm"><thead className="text-xs text-white/40"><tr>{["NAME","PRICE","STOCK","THRESHOLD","ACTIONS"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={5} className="px-3 py-10 text-center text-white/30">Loading...</td></tr>:items.map(p=><tr key={p.id} className="border-t border-white/5"><td className="px-3 py-4">{p.name}</td><td className="px-3 py-4">₦{Number(p.price).toLocaleString()}</td><td className="px-3 py-4">{p.stock_quantity}</td><td className="px-3 py-4">{p.low_stock_threshold ?? 0}</td><td className="px-3 py-4"><button onClick={()=>adjust(p.id,1)} className="mr-3 text-green-400">+1</button><button onClick={()=>adjust(p.id,-1)} className="mr-3 text-orange-400" disabled={p.stock_quantity<=0}>-1</button><button onClick={()=>edit(p)} className="mr-3 text-orange-400">Edit</button><button onClick={()=>remove(p.id)} className="text-red-400">Delete</button></td></tr>)}</tbody></table></div></div></main>}
