"use client";
import { useEffect,useMemo,useState } from "react";
import { api } from "@/lib/api";
type Product={id:number;name:string;price:string|number;stock_quantity:number};type CartItem={product:Product;quantity:number};
export default function SalesPage(){const[products,setProducts]=useState<Product[]>([]);const[cart,setCart]=useState<CartItem[]>([]);const[q,setQ]=useState("");const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);const[message,setMessage]=useState("");const[storeId,setStoreId]=useState<number|null>(null);
async function load(){setLoading(true);try{const{user}=await api<{user:{store_id:number|null}}>("/auth/me");if(!user.store_id)throw new Error("No store is associated with this account");setStoreId(user.store_id);const d=await api<{products:Product[]}>(`/product/list?store_id=${user.store_id}`);setProducts(d.products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())))}catch(e){setMessage(e instanceof Error?e.message:"Unable to load products")}finally{setLoading(false)}}useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[q]);
function add(p:Product){setCart(c=>{const f=c.find(x=>x.product.id===p.id);if(f)return c.map(x=>x.product.id===p.id?{...x,quantity:Math.min(x.quantity+1,p.stock_quantity)}:x);return[...c,{product:p,quantity:1}]})}
function change(id:number,d:number){setCart(c=>c.flatMap(x=>x.product.id===id?((x.quantity+d<=0)?[]:[{...x,quantity:Math.min(x.quantity+d,x.product.stock_quantity)}]):[x]))}
const total=useMemo(()=>cart.reduce((s,x)=>s+Number(x.product.price)*x.quantity,0),[cart]);
async function complete(){if(!cart.length||!storeId)return;setSubmitting(true);setMessage("");try{const d=await api<{receipt:{sale_id:number;total_amount:string}}>("/sales",{method:"POST",json:{store_id:storeId,items:cart.map(x=>({product_id:x.product.id,quantity:x.quantity})),client_transaction_id:crypto.randomUUID()}});setMessage(`Sale completed. Receipt #${d.receipt.sale_id}`);setCart([]);load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to complete sale")}finally{setSubmitting(false)}}
return <main className="min-h-screen bg-[#0b0b0b] p-5 text-white md:p-8"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-semibold">Sales</h1>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-orange-300">{message}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-white/10 bg-[#151515] p-5"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="font-semibold">Products</h2><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..." className="field max-w-sm"/></div>{loading?<p className="py-12 text-center text-white/40">Loading...</p>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map(p=><article key={p.id} className="rounded-xl border border-white/10 bg-[#101010] p-4"><div className="mb-6 h-20 rounded-lg bg-white/5"/><h3 className="font-medium">{p.name}</h3><p className="mt-1 text-orange-400">₦{Number(p.price).toLocaleString()}</p><p className="mt-1 text-xs text-white/40">{p.stock_quantity} in stock</p><button disabled={!p.stock_quantity} onClick={()=>add(p)} className="mt-4 w-full rounded-lg bg-orange-500 px-3 py-2 text-sm font-semibold text-black disabled:bg-white/10 disabled:text-white/30">{p.stock_quantity?"Add to cart":"Out of stock"}</button></article>)}</div>}</section><aside className="h-fit rounded-2xl border border-white/10 bg-[#151515] p-5"><h2 className="mb-5 font-semibold">Cart</h2><div className="min-h-32 space-y-2">{cart.length?cart.map(x=><div key={x.product.id} className="flex items-center justify-between rounded-lg bg-white/5 px-3 py-2 text-sm"><div><p>{x.product.name}</p><p className="text-xs text-white/40">₦{Number(x.product.price).toLocaleString()} × {x.quantity}</p></div><div className="flex items-center gap-2"><button onClick={()=>change(x.product.id,-1)} className="rounded bg-white/10 px-2">−</button><button onClick={()=>change(x.product.id,1)} className="rounded bg-white/10 px-2">+</button></div></div>):<p className="py-8 text-center text-sm text-white/30">Cart is empty</p>}</div><div className="my-5 flex justify-between border-t border-white/10 pt-4"><span>Total</span><strong>₦{total.toLocaleString()}</strong></div><button disabled={!cart.length||submitting} onClick={complete} className="w-full rounded-xl bg-orange-500 py-3 font-semibold text-black disabled:bg-white/10 disabled:text-white/30">{submitting?"Processing...":"Complete Sale"}</button></aside></div></div></main>}
