import Link from "next/link";

export default function ManagerDashboard() {
  return <Shell><Header title="Manager Dashboard" user="Jane Manager" role="manager" /><div className="grid gap-5 lg:grid-cols-2"><Section title="Alerts"><Placeholder text="No alerts right now." /></Section><Section title="Performance Snapshot"><Placeholder text="Performance metrics coming soon." /></Section><Section title="Reports Overview"><Placeholder text="Reports overview coming soon." /><Link href="/report" className="mt-4 inline-block text-sm font-medium text-orange-400">View Full Report →</Link></Section><Section title="Recent Transactions" className="lg:col-span-2"><Table /></Section><Section title="Staff Activity"><Placeholder text="Staff activity coming soon." /><Link href="/users" className="mt-4 inline-block text-sm font-medium text-orange-400">View Staff →</Link></Section><Section title="Inventory Highlights"><Placeholder text="Inventory highlights coming soon." /><Link href="/inventory" className="mt-4 inline-block text-sm font-medium text-orange-400">View Inventory →</Link></Section></div></Shell>;
}
function Shell({ children }: { children: React.ReactNode }) { const links=["Dashboard","Sales","Items","Inventory","Transactions","Purchases","Reports","Notifications","Settings"]; return <div className="min-h-screen bg-[#0b0b0b] text-white lg:flex"><aside className="hidden w-64 border-r border-white/10 bg-[#111] p-5 lg:block"><p className="mb-8 text-xl font-bold">TX <span className="text-orange-500">RetailOS</span></p>{links.map(x=><Link key={x} href={x==="Dashboard"?"/manager-dashboard":`/${x.toLowerCase()}`} className="block rounded-lg px-3 py-2.5 text-sm text-white/60 hover:bg-white/5 hover:text-white">{x}</Link>)}</aside><main className="flex-1"><div className="border-b border-white/10 px-5 py-4"><span className="text-sm text-white/40">manager</span></div><div className="p-5 md:p-8">{children}</div></main></div>; }
function Header({title,user,role}:{title:string;user:string;role:string}) { return <div className="mb-7"><p className="text-sm text-white/40">{user} ({role})</p><h1 className="mt-1 text-2xl font-semibold">{title}</h1></div>; }
function Section({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}) { return <section className={`rounded-2xl border border-white/10 bg-[#151515] p-5 ${className}`}><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>; }
function Placeholder({text}:{text:string}) { return <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">{text}</div>; }
function Table() { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-white/40"><tr><th className="px-3 py-3">DATE</th><th className="px-3 py-3">REF</th><th className="px-3 py-3">AMOUNT</th><th className="px-3 py-3">STATUS</th></tr></thead><tbody><tr><td colSpan={4} className="px-3 py-10 text-center text-white/30">No transactions yet</td></tr></tbody></table></div>; }
